version: '3.8'

services:
  app:
    image: 'starwars:latest'
    build:
      context: .
    container_name: StarWars
    ports:
      - 8080:8080
    depends_on:
      - "star-wars-db"
    networks:
      - star-wars
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://star-wars-db:5432/obiwan"

  star-wars-db:
    image: 'postgres:13.1-alpine'
    container_name: star-wars-db
    ports:
      - 5432:5432
    networks:
      - star-wars
    environment:
      - POSTGRES_USER=obiwan
      - POSTGRES_PASSWORD=kenobi

networks:
  star-wars:
    driver: bridge